import 'package:flutter/material.dart';
import 'package:testapp/UIs/test/Custom%20Path/custom_path_model.dart';

List<List<CustomPathModel>>? customPathData = [
  [
    CustomPathModel(pathType: PathType.move, cords: [0.5, 0.88], page: 1),
  ],
  [
    CustomPathModel(pathType: PathType.linear, cords: [0.3, 0.73], page: 1),
    CustomPathModel(pathType: PathType.linear, cords: [0.2, 0.7], page: 1),
    CustomPathModel(pathType: PathType.linear, cords: [0.33, 0.66], page: 1),
  ],
  [
    CustomPathModel(pathType: PathType.linear, cords: [0.5, 0.59], page: 1),
    CustomPathModel(pathType: PathType.linear, cords: [0.67, 0.47], page: 1),
  ],
  [
    CustomPathModel(pathType: PathType.linear, cords: [0.74, 0.445], page: 1),
    CustomPathModel(pathType: PathType.linear, cords: [0.4, 0.34], page: 1),
    CustomPathModel(pathType: PathType.linear, cords: [0.26, 0.3], page: 1),
    CustomPathModel(pathType: PathType.linear, cords: [0.26, 0.2], page: 1),
  ],
  [
    CustomPathModel(pathType: PathType.linear, cords: [0.2, 0.18], page: 1),
    CustomPathModel(pathType: PathType.linear, cords: [0.72, 0.12], page: 1),
  ],
  [
    CustomPathModel(pathType: PathType.linear, cords: [0.8, 0.09], page: 1),
    CustomPathModel(pathType: PathType.linear, cords: [0.5, 0.0], page: 1),
    CustomPathModel(pathType: PathType.linear, cords: [0.44, 0.98], page: 2),
  ],
  [
    CustomPathModel(pathType: PathType.linear, cords: [0.35, 0.95], page: 2),
    CustomPathModel(pathType: PathType.linear, cords: [0.7, 0.835], page: 2),
  ]
];

final List<PathItemModel> customPathItemsList = [
  PathItemModel(
    asset: "assets/custompathassets/base1.svg",
    colors: [],
    dx: 0.3305,
    dy: 0.0991,
    page: 1,
    width: 0.2873,
    height: 0.0985,
    dz: 2,
    level: 1,
    isBase: true,
    source: "AST",
    type: "SVG",
  ),
  PathItemModel(
    asset: "assets/custompathassets/ladder_f.svg",
    colors: [Colors.grey, Colors.amber, Colors.amberAccent],
    dx: 0.0621,
    dy: 0.1572,
    page: 1,
    width: 0.5262,
    height: 0.1551,
    dz: 1,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/p2.svg", // "jointer",
    dx: 0.0705,
    dy: 0.2813,
    page: 1,
    width: 0.2674,
    height: 0.0991,
    dz: 0,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/base2.svg",
    colors: [],
    dx: 0.1991,
    dy: 0.3332,
    page: 1,
    width: 0.435,
    height: 0.1314,
    dz: 2,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/p3.svg",
    colors: [],
    dx: 0.3653,
    dy: 0.421,
    page: 1,
    width: 0.4905,
    height: 0.1429,
    dz: 1,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/base3.svg",
    colors: [],
    dx: 0.6106,
    dy: 0.5247,
    page: 1,
    width: 0.2948,
    height: 0.0894,
    dz: 2,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/path4.svg",
    colors: [],
    dx: 0.356,
    dy: 0.5794,
    page: 1,
    width: 0.3674,
    height: 0.1151,
    dz: 1,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/base4.svg",
    colors: [],
    dx: 0.2053,
    dy: 0.6548,
    page: 1,
    width: 0.2598,
    height: 0.0847,
    dz: 0,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/path5.svg",
    colors: [],
    dx: 0.2213,
    dy: 0.7167,
    page: 1,
    width: 0.0696,
    height: 0.1046,
    dz: 0,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/base5.svg",
    colors: [],
    dx: 0.008,
    dy: 0.7973,
    page: 1,
    width: 0.3378,
    height: 0.0992,
    dz: 0,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/path6.svg",
    colors: [],
    dx: 0.216,
    dy: 0.8596,
    page: 1,
    width: 0.4853,
    height: 0.0677,
    dz: 0,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/base6.svg",
    colors: [],
    dx: 0.624,
    dy: 0.878,
    page: 1,
    width: 0.3386,
    height: 0.1133,
    dz: 4,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/path7.svg",
    colors: [],
    dx: 0.464,
    dy: 0.9399,
    page: 1,
    width: 0.2805,
    height: 0.0822,
    dz: 3,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/base7.svg",
    colors: [],
    dx: 0.0906,
    dy: 0.9418,
    page: 1,
    width: 0.4506,
    height: 0.1382,
    dz: 2,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
  PathItemModel(
    asset: "assets/custompathassets/path8.svg",
    colors: [],
    dx: 0.3973,
    dy: 1.0419,
    page: 1,
    width: 0.2961,
    height: 0.0947,
    dz: 1,
    level: 1,
    isBase: true,
    source: "AST",
    type: 'SVG',
  ),
];

final List<MilestoneModel> milestones = [
  MilestoneModel(
      asset: "assets/custompathassets/ml0.png",
      width: 0.1177,
      height: 0.0824,
      dx: 0.43,
      dy: 0.1528,
      animType: "NONE",
      assetType: "PNG",
      description: "Watch Walkthrough and win 100 Tokens to get started!",
      rewards: [
        Reward(amount: 100, type: "FLC"),
      ],
      route: "/walkthrough",
      isCompleted: true),
  MilestoneModel(
    asset: "assets/custompathassets/ml1.png",
    width: 0.1491,
    height: 0.0904,
    dx: 0.348,
    dy: 0.3877,
    animType: "FLOAT",
    assetType: "PNG",
    description: "Complete your profile and get 200 Tokens and ₹50",
    rewards: [
      Reward(amount: 200, type: "FLC"),
      Reward(amount: 50, type: "Money"),
    ],
    route: "/profile",
  ),
  MilestoneModel(
    asset: "assets/custompathassets/ml2.png",
    width: 0.1158,
    height: 0.094,
    dx: 0.704,
    dy: 0.5673,
    animType: "FLOAT",
    assetType: "PNG",
    description: "Do some task",
    rewards: [
      Reward(amount: 200, type: "FLC"),
      Reward(amount: 50, type: "Money"),
    ],
    route: "/profile",
  ),
  MilestoneModel(
    asset: "assets/custompathassets/ml3.png",
    width: 0.1284,
    height: 0.0722,
    dx: 0.2692,
    dy: 0.6939,
    animType: "ROTATE",
    assetType: "PNG",
    description: "Do some task",
    rewards: [
      Reward(amount: 200, type: "FLC"),
      Reward(amount: 50, type: "Money"),
    ],
    route: "/task",
  ),
  MilestoneModel(
    asset: "assets/custompathassets/ml4.png",
    width: 0.16,
    height: 0.0908,
    dx: 0.08,
    dy: 0.8291,
    animType: "NONE",
    assetType: "PNG",
    description: "Do some task",
    rewards: [
      Reward(amount: 200, type: "FLC"),
      Reward(amount: 50, type: "Money"),
    ],
    route: "/task",
  ),
  MilestoneModel(
    asset: "assets/custompathassets/ml5.png",
    width: 0.1449,
    height: 0.1629,
    dx: 0.712,
    dy: 0.9121,
    animType: "FLOAT",
    assetType: "PNG",
    description: "Do some task",
    rewards: [
      Reward(amount: 200, type: "FLC"),
      Reward(amount: 50, type: "Money"),
    ],
    route: "/task",
  ),
  MilestoneModel(
    asset: "assets/custompathassets/ml6.png",
    width: 0.213,
    height: 0.0868,
    dx: 0.2106,
    dy: 1.0207,
    animType: "NONE",
    assetType: "PNG",
    description: "Do some task",
    rewards: [
      Reward(amount: 200, type: "FLC"),
      Reward(amount: 50, type: "Money"),
    ],
    route: "/task",
  ),
];
